package com.zz.controller;

import com.zz.model.User;
import com.zz.model.ResponseObject;
import com.zz.repository.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import org.springframework.http.ResponseEntity;

@Controller // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @PostMapping(path="/add", produces = MediaType.APPLICATION_JSON_VALUE) // Map ONLY POST Requests
    public @ResponseBody ResponseObject<User> addNewUser (@RequestBody User user) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        if (userRepository.existsByUserName(user.getUserName())) {
            return ResponseObject.error(400, "用户名已经存在");
        }
        userRepository.save(user);
        return ResponseObject.success(user);
    }

    @GetMapping(path="/all", produces = MediaType.APPLICATION_JSON_VALUE)
    public @ResponseBody ResponseEntity<ResponseObject<Iterable<User>>> getAllUsers() {
        Iterable<User> users = userRepository.findAll();
        // This returns a JSON or XML with the users
        users.forEach(user -> System.out.println(user.getUserName()));
//        System.out.println(users);
        return ResponseEntity.ok(ResponseObject.success(users));
    }

}