package com.zz.controller;

import com.zz.model.User;
import com.zz.response.HttpStatus;
import com.zz.response.ResponseObject;
import com.zz.repository.UserRepository;
import com.zz.security.JwtUtil;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import org.springframework.http.ResponseEntity;

import java.util.HashMap;
import java.util.Map;

@RestController // This means that this class is a Controller
@RequestMapping(path="/user") // This means URL's start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @PostMapping(path="/register", produces = MediaType.APPLICATION_JSON_VALUE) // Map ONLY POST Requests
    public ResponseObject<User> addNewUser (@RequestBody User user) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        if (userRepository.existsByUserName(user.getUserName())) {
            return ResponseObject.error(HttpStatus.CONFLICT.getCode(), "用户名已经存在");
        }
        userRepository.save(user);
        return ResponseObject.success(user);
    }

    @PostMapping(path="/login", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseObject<Map<String, Object>> login(@RequestBody User user) {
        if (userRepository.existsByUserNameAndPassword(user.getUserName(), user.getPassword())) {
            User user1 = userRepository.findByUserName(user.getUserName());
            Map<String, Object> map = new HashMap<>(2);
            map.put("userId", user1.getUserId());
            map.put("userName", user.getUserName());
            String token = JwtUtil.generateToken(user.getUserName());
            map.put("token", token);
            return ResponseObject.success(map);
        }
        return ResponseObject.error(HttpStatus.UNAUTHORIZED.getCode(), "用户名或密码错误");
    }

    @GetMapping(path="/all", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseObject<Iterable<User>> getAllUsers(@RequestHeader(name = "Authorization", required = false) String token) {
        System.out.println(token);
        if (JwtUtil.validateToken(token)) {
            return ResponseObject.error(HttpStatus.UNAUTHORIZED.getCode(), "token无效");
        }
        Iterable<User> users = userRepository.findAll();
        return ResponseObject.success(users);
    }

}